workflows:  
  native-android:
    name: Native Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: android/android-native-quick-start
    environment:
      android_signing:
        - codemagic
      groups:
        - google_credentials
      vars:
        PACKAGE_NAME: "io.codemagic.androidquicksample"
    scripts:
      - name: Set Android SDK location
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          chmod +x gradlew
          LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name '$PACKAGE_NAME')
          if [ -z LATEST_BUILD_NUMBER ]; then
              # fallback in case no build number was found from google play. Alternatively, you can `exit 1` to fail the build
              UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          else
              UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
          fi
          ./gradlew bundleRelease -PversionCode=$UPDATED_BUILD_NUMBER -PversionName=1.0.$UPDATED_BUILD_NUMBER
    artifacts:
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - wyatt1115@gmail.com
        notify:
          success: true
          failure: true
      scripts:
        - name: Publish to Google Cloud
          script: | 
            echo $GCLOUD_STORAGE_KEY > $CM_BUILD_DIR/gcloud_storage_key.json
            gcloud auth activate-service-account --key-file $CM_BUILD_DIR/gcloud_storage_key.json
            gsutil cp $CM_BUILD_DIR/app/build/outputs/**/*.aab gs://codemagic777 
      


